Feature/registration
nurgeld/TaskManager pull request #8
Opened 2022-10-28 18:38 UTC by nurgeld

2022-10-29 19:11 UTC, greybutton requested changes
> [Merge branch 'develop' of](https://github.com/nurgeld/TaskManager/pull/8/commits/73e43b98eb4e89ae673350634e0b2192f4e5367b) https://github.com/nurgeld/TaskManager [into…](https://github.com/nurgeld/TaskManager/pull/8/commits/73e43b98eb4e89ae673350634e0b2192f4e5367b) 
… feature/registration

таких коммитов быть не должно. девелоп никогда не мержится в фича ветку. если нужны изменения из девелопа в фича ветки, то фича ветку нужно ребейзить от девелопа

2022-10-29 19:11 UTC, greybutton commented on config/initializers/simple_form_materialize.rb
> +  end
отступы уехали

2022-10-30 09:54 UTC, nurgeld commented
> > [Merge branch 'develop' of](https://github.com/nurgeld/TaskManager/pull/8/commits/73e43b98eb4e89ae673350634e0b2192f4e5367b) https://github.com/nurgeld/TaskManager [into…](https://github.com/nurgeld/TaskManager/pull/8/commits/73e43b98eb4e89ae673350634e0b2192f4e5367b)
> > … feature/registration
> 
> таких коммитов быть не должно. девелоп никогда не мержится в фича ветку. если нужны изменения из девелопа в фича ветки, то фича ветку нужно ребейзить от девелопа



> > [Merge branch 'develop' of](https://github.com/nurgeld/TaskManager/pull/8/commits/73e43b98eb4e89ae673350634e0b2192f4e5367b) https://github.com/nurgeld/TaskManager [into…](https://github.com/nurgeld/TaskManager/pull/8/commits/73e43b98eb4e89ae673350634e0b2192f4e5367b)
> > … feature/registration
> 
> таких коммитов быть не должно. девелоп никогда не мержится в фича ветку. если нужны изменения из девелопа в фича ветки, то фича ветку нужно ребейзить от девелопа

чтобы это исправить, нужно вернуться к предыдущему коммиту (до ребейза) и слить обновления из девелопа в фича-ветку командой `git pull`? А затем уже последовательно повторить изменения (либо как-то перенести коммиты, сделанные после некорректного ребейза)?

2022-10-30 19:40 UTC, greybutton commented
вот так сделать
```
git switch develop
git pull --rebase
git switch feature/branch
git rebase develop
```

2022-11-01 18:32 UTC, nurgeld commented
> вот так сделать
> 
> ```
> git switch develop
> git pull --rebase
> git switch feature/branch
> git rebase develop
> ```

Спасибо! Изначально я про этот ребейз в нескольких источниках читал , но в итоге все равно все напутал:( 
Сейчас сделал по инструкции и запушил с --force. Конфликты вроде разрешил с учетом того что нужно было оставить.

2022-11-01 19:27 UTC, greybutton approved these changes

2022-11-02 04:06 UTC, merged